
Start Training: Epoch 1
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    main(args)
  File "train.py", line 25, in main
    trainer.run(args, train_data, valid_data)
  File "/opt/ml/input/code/dkt/dkt/trainer.py", line 36, in run
    train_auc, train_acc, train_loss = train(
  File "/opt/ml/input/code/dkt/dkt/trainer.py", line 92, in train
    loss = compute_loss(preds, targets)
  File "/opt/ml/input/code/dkt/dkt/trainer.py", line 253, in compute_loss
    loss = get_criterion(preds, targets)
  File "/opt/ml/input/code/dkt/dkt/criterion.py", line 7, in get_criterion
    return loss(pred, target)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 603, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2906, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([64, 20])) that is different to the input size (torch.Size([64, 40])) is deprecated. Please ensure they have the same size.